### ISSUE TITLE
periodic problems

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#148]

**Comment by oblonski** [comment]
Contribution from Philip Welch (opendoorlogistics):

For periodic problems you usually have a location that needs visiting X times within a period of length Y, where visits have to be spaced out. For example, you could have a 4 week period and need to visit a location 2 times, so you could either visit on week 1 and week 3 OR week 2 and week 4 (but not week 1, week 2).

You therefore have to choose both a visit pattern (week 1, week 3 OR week 2, week 4) and then allocate stops to routes for that pattern. Typically in the literature they select a pattern for each location, optimise the VRP according to the selected patterns and then every few iterations (10 iterations? 100? not sure how many) they try switching the patterns. For a very simple approach, you could try switching the pattern every iteration to begin with though. 

So, lets assume that we associate different days to different vehicles (e.g. one real life vehicle might be modelled as 'Vehicle A day 1', 'Vehicle A day 2' etc... We then lock down stops to only be delivered on set days - either by using the skills somehow or some clever use of time windows. We therefore have a stop which can only be served on week 2 (for example) and a set of vehicles with a subset of vehicles that correspond to days on week 2. So far I think this can be done - or very nearly can be done - within current jsprit.

Lets assume we then define a group of jobs within jsprit (all corresponding to the same location) where each group actually contains several subgroups corresponding to each one of the different patterns. (i.e. one group corresponding to stops which can only be served on week 2, week 4 and another which can only be served on week 1, week 3). We then:

- Ensure that all stops within the same group are removed in the ruin step. (Never leave a group half loaded)

- Only load stops from a single subgroup within the group. (Never do two patterns at once).

- On the recreate step, loop through each subgroup, 
      - inserting all stops within a subgroup, recording the cost, and then removing them again.
      - finally insert the best subgroup found

We then have a periodic solver - although as said we may need an option to retain the same subgroup for X number of iterations. Certainly for smaller periodic problems we could just do this every iteration though.

Does this make sense?

The alternative groups would likely also be useful for different problems too (it can be used to solve some 2-echelon problems and occurs in arc routing as well - although arc routing would need some more developments).

**Comment by juancruzmartino** [comment]
@oblonski do you have an example on this?

**Comment by juancruzmartino** [comment]
how about @PGWelch ?
