### ISSUE TITLE
add reason for unassigned jobs

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#180]

**Comment by oblonski** [comment]
which is not that easy since there might be several reasons

**Comment by oblonski** [comment]
Soe wrote:
"The other suggestion that I have is, when there are unassigned jobs (VRP api), 
it would be good to know why they can't fit in. Probably add a reason for each unassigned job."

**Comment by PGWelch** [comment]
Return the names of the constraints that fail?

**Comment by davidmir** [comment]
This would be great ! Return restrictions that failed was a good chance.

**Comment by oblonski** [comment]
@PGWelch good idea. the problem - I see - here is that the same job can trigger different constraints to fail. In some route, insertion fails since there is not capacity anymore. Other routes cannot insert it due to skill or time constaints etc.. What I can try is to memorize each and every constraint break and then deduct an estimation from a distribution of failed constaints? Other ideas?

**Comment by PGWelch** [comment]
You could just return a structure with, for each vehicle, the constraint that failed (for a route level failure) or a count of each time a constraint failed for position level constraint failures? If you had a route level failure you wouldn't need to bother reporting or testing other constraints at the position level? The data structure will be complex but it would be up to the client code to process it into a higher-level overview if needed? Separating vehicle time window failures from stop time window failures would be good.

**Comment by rsachdeva9355** [comment]
@oblonski  : Is anyone working on it?

**Comment by oblonski** [comment]
Unfortunately, we do not work on it currently.

Am 10/03/16 um 12:11 schrieb rsachdeva9355:

**Comment by oblonski** [comment]
ToDo:
- [ ] unit tests for ReasonTracker to make sure that if constraint name changes, tests fail

**Comment by oblonski** [comment]
Just add this to track reasons of unassigned jobs:

```
UnassignedJobReasonTracker reasonTracker = new UnassignedJobReasonTracker();
algorithm.addListener(reasonTracker);
```

If you want to add a new code and reason for your own constraint (e.g. MySimpleHardConstraint.java), just do the following

```
reasonTracker.put("MySimpleHardConstraint",20, "cannot assign since my own constraint failed");
```
```

**Comment by PGWelch** [comment]
nice!

**Comment by oblonski** [comment]
lets see how it works.
