### ISSUE TITLE
Shall we use logging facade rather than log4j2?

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#185]
as described here:
http://stackoverflow.com/questions/9740569/logger-for-java-library

since the way we do it now forces users to use log4j2

**Comment by oblonski** [comment]
see also Geoffrey's and Peter's discussion:
https://github.com/graphhopper/graphhopper/issues/250

**Comment by davisd123** [comment]
Will send through a POM for stuff I've been working on as a guide.

My application uses logback; integrated graphhopper (slf4j) and jsprit (log4j2) and all modules log.

**Comment by oblonski** [comment]
@davisd123  :+1:

**Comment by oblonski** [comment]
Switch to slf4j: https://github.com/graphhopper/jsprit/tree/migrate-SLF4j which is an abstration layer for logging.
This means when using jsprit one needs to configure logging oneself. However, one can choose which logger to use. 
If you choose log4j, you need to add the [slf4j-log4j binding, the log4j logger](https://github.com/graphhopper/jsprit/blob/migrate-SLF4j/jsprit-examples/pom.xml#L60) (lines 60-70) as well as the [log4j configuration](https://github.com/graphhopper/jsprit/blob/migrate-SLF4j/jsprit-examples/src/main/resources/log4j2.xml) to your project.

**Comment by oblonski** [comment]
via https://github.com/graphhopper/jsprit/commit/1fc8dd0d875609a7ec90409ecb1c1d9ca7a48be5
