### ISSUE TITLE
breaks need to be added to xml reader/writer

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#208]
* [VrpXMLReader](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/problem/io/VrpXMLReader.java) 
* [VrpXMLwriter](https://github.com/jsprit/jsprit/blob/master/jsprit-core/src/main/java/jsprit/core/problem/io/VrpXMLWriter.java)

Does anybody want to do this? See also https://discuss.graphhopper.com/t/you-want-to-contribute-but-dont-know-how/394

**Comment by braktar** [comment]
#227

**Comment by oblonski** [comment]
Thanks. Can we close it @braktar ?

**Comment by braktar** [comment]
Yes, I think so

**Comment by oblonski** [comment]
Perfect!
