### ISSUE TITLE
make jsprit available in maven central

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#217]

**Comment by karussell** [comment]
If you need help here - let me know :) !

Once you get used to it this can be done relatively fast (within ~15min ;))

This issue depends on #215 which needs to be done before.

**Comment by MitchK** [comment]
Any updates on this? We would like to use it for a project, but our technical infrastructure mirrors Maven Central.

**Comment by oblonski** [comment]
Not yet. It will be available along with the next release (in 1-2 months). Do you have any problems using the current repository?

**Comment by MitchK** [comment]
The problem is that my company's internal Nexus server mirrors Maven Central and we're currently not allowed to take stuff from anywhere else.

**Comment by oblonski** [comment]
Ah ok ... as written will do this asap. For the time being, you need to build it yourself. Probably, you already did that, if not:

```
git clone https://github.com/graphhopper/jsprit.git
cd jsprit
mvn install
```

**Comment by MitchK** [comment]
Thanks!

**Comment by karussell** [comment]
@oblonski do you already have a branch where you made the necessary modifications to the pom.xml? If not, I can work on it

**Comment by oblonski** [comment]
Happy to announce that jsprit is now available in Maven Central!
To use jsprit-core of the release candidate v1.7, you just need to add the following dependency (with no explicit repository)

```
<dependency>
    <groupId>com.graphhopper</groupId>
    <artifactId>jsprit-core</artifactId>
    <version>1.7-RC1</version>
</dependency>
```

**Comment by karussell** [comment]
Looks good :) http://search.maven.org/#search%7Cga%7C1%7Cjsprit

**Comment by sgift** [comment]
Would it be possible to add source (https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html) to Maven Central? Would make it a bit easier to explore the sourcecode directly from Maven.

**Comment by karussell** [comment]
@sgift they should be already there, see my link and click sources.jar etc

**Comment by sgift** [comment]
Thanks for the hint, didn't see them before (and IntelliJ wasn't able to load them directly for some reason) .

**Comment by karussell** [comment]
@sgift okay, so it still does not work? Can you trigger explicit source and javadoc download in IntelliJ?

**Comment by sgift** [comment]
@karussell Triggering the download by hand did work, but it wasn't able to automatically match the source.jar with the normal jar. I had to attach the sources by hand after the download, now it works.

**Comment by karussell** [comment]
Ok, looks like an IDE problem! I tried it with NetBeans and it works.
