### ISSUE TITLE
JobNeighborhoods as an external parameter

### ISSUE THREAD

**Issue by Wolf-aru-81** [graphhopper/jsprit#219]
I would like to set my own strategy to build JobNeighborhoods.

If I use the JSprit out of box config to set up the algorithm, JobNeighborhoods are set with a half of near jobs for each job. If I desire to set only 1/3 part of near jobs, I can't.

I think its a good feature because with a good JobNeighborhoods the algorithm can be converging fastest to the result.

**Comment by oblonski** [comment]
Ohh somehow I must have overlooked this. Do you already have "better" neighborhoods even I know it is dependent on the problem to solve?

**Comment by oblonski** [comment]
I think it does not make much sense to provide an entry point for defining the neighborhood for a specific ruin strategy in the out-of-box Jsprit algorithm. However, you can always define your own algorithm with your own ruin and insertion strategies. This way you can also specify your neighborhood. Just look at the Jsprit.class to see how I did it. 
Therefore, I close this for now.
