### ISSUE TITLE
Can I use jsprit in order to matching trajectories? 

### ISSUE THREAD

**Issue by gdiodato** [graphhopper/jsprit#220]
Hi All,
My project is a carpooling application (web and mobile) like Blablacar but for  a short distance.
Our Search section do his work but we want improve the routing matching algorithm.
Users (passengers) have to fill this required fields when they search a trip:
- Origin,
- Destination (postigis coordinates),
- max waiting time
- max walking distance 
- time window (day and hour).

The users (Drivers), instead, offers their rides filling this fields:
- Origin,
- Destination,
- seats available,
- trip preferences (smoke, music, etc.. number from 1 to 5),
- time window (day and hour).

Every user's profile contains trip preferences by default and can be changed every moment.
Our target is return an optimal list of trip offers with trajectory, time window and especially preferences when a user search a particular trip in our search section.

Sprit can we help?

Sincerely,
Gianluca

**Comment by karussell** [comment]
Sounds like a nice project - would you mind using our forum for questions instead of the issues? https://discuss.graphhopper.com

**Comment by karussell** [comment]
Thanks - is now asked here: https://discuss.graphhopper.com/t/can-i-use-jsprit-in-order-to-matching-trajectories/562
