### ISSUE TITLE
Java8 Error

### ISSUE THREAD

**Issue by braktar** [graphhopper/jsprit#236]
Hello, 

I just updated my version of java today and got some errors when building the javadoc of jsprit-core.

Most of those are : 

> error: self-closing element not allowed
>      * `<p/>`

The self-closing elements as `<p/>` or `<br/>` are no more allowed :(

**Comment by oblonski** [comment]
https://stackoverflow.com/questions/26049329/javadoc-in-jdk-8-invalid-self-closing-element-not-allowed 
Thus we should replace `<p/>` by `<p>` and `<br/>` by `<br>`
