### ISSUE TITLE
Serving larger shipments/ Partial delivery

### ISSUE THREAD

**Issue by Bhoumik-s** [graphhopper/jsprit#241]
In cases where the quantity of shipment is larger than capacity of largest vehicle the shipment is not served. In reality larger shipment is broken into smaller pieces and are served by multiple trucks. Is there a optimized way to break shipment into more than one piece and serve by multiple truck and also optimize it.

**Comment by oblonski** [comment]
I think this is a question. Please use our forum: https://discuss.graphhopper.com/. Let us discuss it there and then we might formulate a feature request here.
