### ISSUE TITLE
assign priorities to jobs

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#242]
Often there are more customers than the available vehicle fleet can serve. Then it would be nice to assign priorities to customers that must be served to differentiate them from those that can be served later or omitted at all.

**Comment by oblonski** [comment]
I d suggest to introduce 3 priority levels: 1 = high, 2 = normal and 3 = low. As far as I can judge it now, it should be an appropriate differentiation (at least I do not know why we would need more levels).

**Comment by oblonski** [comment]
seems to work :)

**Comment by jsroyal** [comment]
Is is still work priority for assinging for services?
I run the priority example and it out have some strange exprience.
So is really work or not.
Please help, I newbie with VRP

**Comment by oblonski** [comment]
Can you explain what the problem is? What does not work when using priorities?

**Comment by jsroyal** [comment]
Hi! @oblonski
I running this example to a variable the value of priority but it does not give expected value.
```
Service service1 = Service.Builder.newInstance("1").setPriority(2).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 7)).build();
        Service service2 = Service.Builder.newInstance("2").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 13)).build();

        Service service3 = Service.Builder.newInstance("3").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 7)).build();
        Service service4 = Service.Builder.newInstance("4").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 13)).build();
```

**Comment by oblonski** [comment]
Thanks. What are your expectations?

**Comment by jsroyal** [comment]
Sir @oblonski I was seeing the result in graph stream but the result was strange.
The expectation is like should work according to the priority show the service should be the need to done in this step. -> "1" -> "2" but the output  "2" -> "1".
![image](https://cloud.githubusercontent.com/assets/10773353/26137832/703f6d50-3ae2-11e7-9c45-3ebdf44c35ad.png)

Also, some tweak the in priority it gives me strange result.

**Comment by oblonski** [comment]
Priorties have no impact on the activity sequence at all. If you only had a capacity to serve 2 of your 4 jobs, then the one with higher priority should be prefered. That is the idea.

> Often there are more customers than the available vehicle fleet can serve. Then it would be nice to assign priorities to customers that must be served to differentiate them from those that can be served later or omitted at all.

**Comment by jsroyal** [comment]
Okay, Sir, I got it the priority.
Sir How do I control the activity sequence.
![image](https://cloud.githubusercontent.com/assets/10773353/26152992/1250aab6-3b27-11e7-9285-23a368abdec3.png)
```
Service service1 = Service.Builder.newInstance("1").addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 7)).build();
        Service service2 = Service.Builder.newInstance("2").addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 13)).build();

        Service service3 = Service.Builder.newInstance("3").addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 7)).build();
        Service service4 = Service.Builder.newInstance("4").addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 13)).build();
```
Can I get about it?

**Comment by topcerebro** [comment]
> Hi! @oblonski I running this example to a variable the value of priority but it does not give expected value.
> 
> ```
> Service service1 = Service.Builder.newInstance("1").setPriority(2).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 7)).build();
>         Service service2 = Service.Builder.newInstance("2").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(5, 13)).build();
> 
>         Service service3 = Service.Builder.newInstance("3").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 7)).build();
>         Service service4 = Service.Builder.newInstance("4").setPriority(4).addSizeDimension(WEIGHT_INDEX, 1).setLocation(Location.newInstance(15, 13)).build();
> ```

Priority 2 is assigned by default in the class Service and Shipment: private int priority = 2;.

So using priority=2 is the same as not using it.
Using priority > 2, means decreasing the priority by default.
