### ISSUE TITLE
Error mounting Jsprit on Eclipse

### ISSUE THREAD

**Issue by paulorocosta** [graphhopper/jsprit#252]
Hi guys,
I'm new to Maven and I'm trying to create a Maven Prject on Eclipse for JSprit, but I end up having this error message when running jsprit-instances.

Any ideas?
ERROR:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jsprit-instances: Compilation failure -> [Help 1]

**Comment by karussell** [comment]
For questions please use our forum instead: https://discuss.graphhopper.com/c/jsprit
