### ISSUE TITLE
move io to new module jsprit-io

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#253]
to make the core really lightweight and to get rid of two dependencies in core. 
after this jsprit-core just has two dependencies slf4j and commons.math3.

todo:
- [x] new module jsprit-io
- [x] move algorithm.io
- [x] move problem.io
- [x] refine Schrimpf, GreedySchrimpfFactory as well as ThresholdGenerators
- [x] adapt tests to read instances without xml reader

working branch: https://github.com/graphhopper/jsprit/tree/jsprit-io

**Comment by oblonski** [comment]
closed via https://github.com/graphhopper/jsprit/commit/9e6ff24cab3fbb0c9b10eb08f117e4bcea43e124

**Comment by oblonski** [comment]
jsprit-core has now only two dependencies
```
    <dependencies>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.4</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${logger.version}</version>
        </dependency>

</dependencies>
```
Vers nice!!

**Comment by karussell** [comment]
nice! BTW: why math3?

**Comment by oblonski** [comment]
[DBSCANClusterer](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/DBSCANClusterer.java) as well as some descriptive statistics
