### ISSUE TITLE
No specific start point

### ISSUE THREAD

**Issue by arun4444** [graphhopper/jsprit#254]
Hello,

I have been trying to ascertain the features of this wonderful library. It seems to satisfy the needs of our project except for one feature. I was unable to build a route with no start points i.e. an arbitrary start location, the truck can start at any of the service locations, and optimize for cost. Is this possible with this library or must i run the algorithm n-times where n is the number of service locations.

**Comment by braktar** [comment]
Currently the start point is necessary.

But I've worked few weeks to such a feature.

https://github.com/braktar/jsprit/tree/noStart

The firsts tests are working well

**Comment by PGWelch** [comment]
Hi,

If you provide a custom travel matrix, you can just set travel time and cost to be zero from the vehicle start point to all other locations. So you still technically have a start point, but its fake - i.e. it doesn't really do anything. This is what I do in ODL Studio - see screenshot attached - vehicles starting at the first stop they do but returning to the same end depot.

![routes-with-no-start-point-ending-at-same-depot](https://cloud.githubusercontent.com/assets/5254312/16261064/fcf92eae-3861-11e6-9b21-b60d29efc77b.png)

**Comment by oblonski** [comment]
Thanks for your question, and your @braktar @PGWelch valuable answers. 
I assume it is answered. 
PS: Please use our forum for such questions: https://discuss.graphhopper.com/
