### ISSUE TITLE
Vehicle Routing Problems with Profits (VRPP)

### ISSUE THREAD

**Issue by lazaronixon** [graphhopper/jsprit#256]
http://www.unibs.it/sites/default/files/ricerca/allegati/quaderno%20wpdem%203.pdf
Is possible solve this problem creating custom HardConstraints or SoftConstraints ?

**Comment by lazaronixon** [comment]
https://github.com/graphhopper/jsprit/issues/110#issuecomment-47522475

**Comment by oblonski** [comment]
Hi, It is not yet easy to model since each service requires a profit and - most importantly - insertion heuristics should insert according to marginal costs but according to marginal profit. Additionally, the algorithm should also reject jobs if marginal profit < 0.
