### ISSUE TITLE
TimeWindow with negative values

### ISSUE THREAD

**Issue by braktar** [graphhopper/jsprit#257]
Is there a limitation which force to have strict positive time windows ?

This definition of the time is quite static and require some preprocessing in order to shift every value accordingly to the littlest activity or vehicle start. I thought Jsprit should be able to handle those cases.

**Comment by oblonski** [comment]
Oh, sorry. Didnt see this here. 
Can you give me a use case for time windows with negative values? What exactly do you mean with value? Duration?

**Comment by braktar** [comment]
The case is instead of using a standard timestamp, we could use a relative value.
The reference is the plan day at 00:00:00, but it could happen than the loading time could begin the day before and end on the reference day. I.E it could be smth like [-3600,4800]

We could shift all the TWs accordingly to the littlest, and unshift the result in order to get the right informations.

The other way of doing it is to format the date before and cut the negative timewindows ( [0,4800] , but in output we will have some loss of information.

From what i've seen, allow negative values in TimeWindows have any impact on the solve.

**Comment by PGWelch** [comment]
Maybe I'm missing something here, but couldn't you just set the reference time (I.e. the zero time) to be some arbitrarily early time instead? I.e. set it to the earliest possible event?

**Comment by carhartl** [comment]
> couldn't you just set the reference time (I.e. the zero time) to be some arbitrarily early time instead?

We started using the unix epoch time as zero for all timestamps, also to account for when a time might shift to the day before.

**Comment by braktar** [comment]
Time is still relative to something, there is no problem once we set a far enough reference. To me, that's a limitation which have no particular reason but is set because of conventions.
Currently, there is no calendar with a zero which is in the future but who knows, it will maybe happen ;)
