### ISSUE TITLE
Is it possible to add pickup and delivery pairs dynamically?

### ISSUE THREAD

**Issue by willwangcn** [graphhopper/jsprit#262]
Assuming that we have already had solutions for previous requests, and now we have new requests for pickups and deliveries. If we don't want to change the previous routes or change the drivers for the previous requests, we want to add the new requests into the previous routes dynamically. Is it possible to use constraints to meet the demands? Thank you.

**Comment by oblonski** [comment]
Would you mind to use [our forum](https://discuss.graphhopper.com/) for such question? Thank you.
