### ISSUE TITLE
Bug createStateId inside StateUpdater

### ISSUE THREAD

**Issue by lazaronixon** [graphhopper/jsprit#269]
When different statesId are created inside a stateUpdate it throws
java.lang.IllegalArgumentException: arg must not be null
at com.graphhopper.jsprit.core.problem.Capacity.max(Capacity.java:279)

Example here: #268

**Comment by oblonski** [comment]
actually I do not understand this. can you explain again why this is bug?

**Comment by lazaronixon** [comment]
I want to create runtime StateIds. It works with few numbers but not with multiples.
Pull Request is reproducing the problem.

**Comment by oblonski** [comment]
Would you mind to explain why you want to create "runtime StateIds"? This might create millions of new states and blows up the StateManager significantly

**Comment by lazaronixon** [comment]
I have many jobs on same location. I want create a stateId to each location with route, and create a softconstraint to prevent jobs on different routes.

**Comment by oblonski** [comment]
Do you want to specify that the jobs on the same location need to be in the same route?

**Comment by lazaronixon** [comment]
Correct... But I have many locations too..

**Comment by oblonski** [comment]
Ok. I give you an example: If you want to memorize the color of the vehicle that serve a particular location. Then you would create a single state-id called "color-assignment" like this:

`StateId colorAssignment = stateManager.createStateId("color-assigment");`

If you now want to memorize the actual colors, you would iterator over the activities of a route and memorize color like this:

`stateManager.putActivityState(act, vehicle, colorAssignment, "blue");`

assuming that the "vehicle" is blue.

If you need this state somewhere (in your constraints), you can get the color of an activity like this:

`stateManager.getActivityState(act,vehicle,colorAssigment,String.class);`

What I wanted to write is that you do not need to create a new state each time you need to memorize a state. It is just an id (which has an index) you can use to retrieve states.

**Comment by lazaronixon** [comment]
Hum.. Ok. So, it is more a limitation than a bug...
I thought I could create any problemStates I wanted to.

**Comment by lazaronixon** [comment]
Sorry to reopen issue. But i tried multiple ways to solve the problem without sucess.
I almost right that it worked on the past.

[https://groups.google.com/d/msg/jsprit-mailing-list/BXZN7tZybck/GIJJQSOPNDcJ](url)

It will fail dependent of number of jobs...
[https://github.com/jsprit/playground/blob/master/src/stackoverflow/Stackoverflow_RelatedJobs_13_and_21_inSameRoute.java#L74](url)

**Comment by lazaronixon** [comment]
I think i solved the problem with something like 
```
public void visit(TourActivity ta) {
        HashSet<Location> locations = stateManager.getRouteState(route, stateId, HashSet.class);
        locations = firstNonNull(locations, new HashSet());
        locations.add(ta.getLocation());
        stateManager.putRouteState(route, stateId, locations);
}
```
Thank you so much...

**Comment by hrivere** [comment]
I have a very similar situation, would you mind providing the final code (soft constraint and status updater)?

Thank you so much!

**Comment by JO-WTF** [comment]
I believe this is indeed a bug.
@lazaronixon used a workaround to get rid of the error but the problem exists.

Take the JobAndActivityDependenciesExample.java as an example, if I add one-line code as following in line 91, the error occurs:
`stateManager.putProblemState(stateManager.createStateId(((JobActivity) activity).getJob().getId()),VehicleRoute.class,route);`
The problem seems to be related with activity.getJob(). If I use the following code instead, the error is gone:
`stateManager.putProblemState(stateManager.createStateId(((JobActivity) activity).getName()),VehicleRoute.class,route);`

**Comment by solerf** [comment]
I'll leave what I found in case it helps anyone. I was getting the same exception at the same point that @lazaronixon described and found that when creating a new `stateId` that does not exists yet during algorithm execution it resets the state inside [StateManager](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/StateManager.java#L111), in my case the `activityStates`, and every previous information is lost. The solution was creating all needed `stateIds` before starting the execution.
