### ISSUE TITLE
unintended values for considering fixed costs

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#271]
"I think there is something unintended going on in JobInsertionConsideringFixCostsCalculator.java, which could also explain why you can't pin down the impact properly."

Also related to [this](https://discuss.graphhopper.com/t/fixed-vehicle-cost/711).

**Comment by mcrnotts** [comment]
When I managed to get the output set to print SCR, the issue appeared to come from `[main] INFO  jsprit.core.algorithm.InsertionInitialSolutionFactory - create initial solution` where it started at zero and went up from there in the limited iterations. Once it went to the actual solution, `solution_completeness_ratio` went to more reasonable values (though iirc, <0.5 at start), but I assume the algorithm has already chosen its starting vehicles from initial solution? If you're struggling to recreate, is there a listener I can put in to check my examples and pinpoint one faster? I managed to recreate straight away before on first try, now I can't set the output properly :(
