### ISSUE TITLE
Minimize Idle Time

### ISSUE THREAD

**Issue by brancusi** [graphhopper/jsprit#272]
Hi,

Is there a way to manually set the ordering of a route, but minimize the idle time?

Example:
```
store1
Time window: 6am-11am

store2
Time window: 9am-3pm
```
Can I force the route to go:

store1 then store2 but minimize the idle?

Solution should be something like:

```javascript
[
  store1: {
    arrive: "8:15am",
    depart: "8:45am",
    duration: 30
  },
  store2: {
    arrive: "9:30am",
    depart: "9:40am",
    duration: 10
   }
]
```

The reasoning is that we still manually order the route stops for routes that are well established. So we are able to take things like traffic, or construction into account.

The main requirement is that we reduce the idle time, so during the initial route creation process, we need the feedback.

Thank you for open sourcing this project.

**Comment by oblonski** [comment]
Hi @brancusi, Would you mind to use our forum for such questions? Just post it here again: https://discuss.graphhopper.com/c/jsprit and I am sure you will get an answer.
