### ISSUE TITLE
move docs to repository

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#275]
to maintain different versions

**Comment by oblonski** [comment]
see https://github.com/graphhopper/jsprit/commit/249f1acdb3ef08b183a9db396d0a025121e978ee and related

**Comment by oblonski** [comment]
the new folder can be found here: https://github.com/graphhopper/jsprit/tree/master/docs

**Comment by oblonski** [comment]
docs for current versions can be found here. for version <1.7 it is here. thus, docs moved entirely from wiki to doc-folder with version control. wiki is removed.

**Comment by oblonski** [comment]
let me know if you found links that are not accessible anymore and I ll fix this asap

**Comment by karussell** [comment]
Instead of 'before-1.7' I would create a branch '1.6' and use exactly the same, this way you can use only relative links and not point to master directly (makes merging and branching to new versions hard)

**Comment by karussell** [comment]
Ah, and I would keep the wiki for the next 6 months with a link to the new docs location :)

**Comment by oblonski** [comment]
thanks @karussell. done :)
