### ISSUE TITLE
'<' character in "<1.7" branch name is generating git pulling error on windows

### ISSUE THREAD

**Issue by GabrielGreslin** [graphhopper/jsprit#276]
On windows, you can not create a file or folder starting with a '<' character.
Such, git engine cannot pull the branch "<1.7" as it try to create file starting with this name.

> error: cannot lock ref 'refs/remotes/origin/<1.7': Unable to create 'C:/DEV/depot/jsprit/.git/refs/remotes/origin/<1.7.lock': Invalid argument

Solution would be to change the name of this branch.

**Comment by oblonski** [comment]
ok ... I ll change the name :)

**Comment by oblonski** [comment]
here it is https://github.com/graphhopper/jsprit/tree/before_1.7 . does this work for you?

**Comment by GabrielGreslin** [comment]
Yes, i can fetch "before_1.7" without issues.
so "<1.7" could be deleted, isn't ?

**Comment by oblonski** [comment]
yes. deleted. thanks.
