### ISSUE TITLE
Adding constraint related to specific routes.

### ISSUE THREAD

**Issue by reedrefucher** [graphhopper/jsprit#278]
Hello!

Your instrument for routing optimization is gorgeous, easy to use and incredibly fast!
It is very pleased to use it! 

I am still exploring possibilities of ODL, and there is one moment, that I couldn't find nor in text tutorials, neither in videos.   

Here it is:
I want to add constraint related to restriction to use specific part of city roads in a specific moments of day.  So I am wondering, is it possible to exclude such parts from road grid, or add a very big penalty linked to them. 

Thank you in advance for your help!
Dmytro.

**Comment by oblonski** [comment]
Hi, this is not the place to ask questions related to ODL. Please contact info@opendoorlogistics.com. Hope you will find answers there.

**Comment by PGWelch** [comment]
Hi, if ones come along like this can you redirect to [my website](http://www.opendoorlogistics.com) rather than the email address? Its better to keep email addresses off webpages (other than as images) to help reduce spam. Thanks Stefan!

**Comment by oblonski** [comment]
ok. done.

**Comment by PGWelch** [comment]
Thanks!
