### ISSUE TITLE
how to switch early insert pickup location to another vehicle based on HardRouteConstraint or any other way

### ISSUE THREAD

**Issue by mndpsngh21** [graphhopper/jsprit#283]
I am working on below scenario:

Let us take example that I have a service man who is picking food from one restaurant and delivering to customers. Restaurant  provides some offers to customers like some pizzas have free cold drink offer and Delivery boy has limited capacity only and Delivery boy route is planned based on customer orders. Let us suppose Restaurant got 7 pizza offers from different customers and customer who is  farthest from restaurant has order pizza with offer. Now Delivery by has one extra container to deliver.For my scenario i have one Strategy that Algorithm should assign nearer delivery to another delivery boy so that Delivery boy who is delivering to farthest point should have 7 container including offered. Now I am not able to understand that how can I remove initial assignment or how can i start from farthest assignments.

**Comment by oblonski** [comment]
Would you mind to ask this question here: https://discuss.graphhopper.com/c/jsprit?
Thanks a lot!
