### ISSUE TITLE
 How to use latitude and longitude

### ISSUE THREAD

**Issue by kelvinthony** [graphhopper/jsprit#284]
How to use latitude and longitude in this example: 
`//Add Customer `

`vrpBuilder.addJob(Service.Builder.newInstance("1").addSizeDimension(0,18).setLocation(Location.newInstance(22, 22)).build());`

I can insert latitude and longitude here? .
`setLocation(Location.newInstance([Lat], [Long]))`

Thanks for your answers :D

**Comment by oblonski** [comment]
Yes, you can set it this way. The question remains what you intend to do with lon/lat :). For further questions, please use our [forum](https://discuss.graphhopper.com/c/jsprit). Thanks a lot.
