### ISSUE TITLE
add getDistance(..) to VehicleRoutingTransportCosts?

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#290]
As distance is and will be more and more important (electric vehicles), I think it makes sense to add a getDistance(..) ([TransportDistance](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/cost/TransportDistance.java)) method to one of the most important interfaces [VehicleRoutingTransportCosts](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/cost/VehicleRoutingTransportCosts.java). It would break your code, but it would make many things much simpler. 

Any thoughts on this?

**Comment by PGWelch** [comment]
It's probably not a big fix to make in the code that will break (at least it's not a big fix in my code). Why do electric vehicles need distance though as opposed to a cost (which could use distance internally in the getCost method)?

**Comment by oblonski** [comment]
You are correct, internally distance is usually used anyway. But often one needs the distance from A to B, not only when analysing the solution, but also for specific constraints. For example, I want to add a vehicle dependent max-distance constraint here (which is very important for electric vehicles). If this should be part of the core, we need to make sure that we can get the distance. If it is part of VehicleRoutingTranportCosts, it is ensured. 
The other possibility is to let the user add the (a ready to use) max distance constraint. The user then needs to provide the distances from A to B as well as the max distances for each vehicle. Then I actually do not need to change anything. Would you prefer the second option?

**Comment by PGWelch** [comment]
You make a good point that its handy to have distance available if you're creating constraints that use distance...

If its only going to be used on specific constraints, then you could add a default getDistance method to the VehicleRoutingTransportCosts interface (assuming you're using java 8, I think default interface methods only exist in 8) that throws an java.lang.UnsupportedOperationException ? This way you don't break existing code and you only hit the exception if you use a constraint that requires distance. The exception then lets the user know they need to implement the distance method to use that constraint...?

**Comment by oblonski** [comment]
Good to know that you would find it handy as well :). I am thinking about the default method, but maybe I just add it to the VehicleRoutingTransportCost interface. I am still not sure yet ... I could also add a way to the VehicleRoutingProblem to set a distance matrix, thus beside .setRoutingCost(..), .setActivityCosts and would be setDistanceMatrix(..). However, distance is somehow related to TransporTime and Costs and would thus fit into VehicleRoutingTransportCost ... hmm

**Comment by oblonski** [comment]
related to https://github.com/graphhopper/jsprit/commit/f8ea447cb9f6934c41650760c47e07fdbb1d62c9
This way you can add a maxDistance constraint. However, it is currently loosely coupled rather than tightly integrated (which might makes sense as well and might require the getDistance(..) interface as well).

**Comment by calfzhou** [comment]
+1 for adding getDistance to VehicleRoutingTransportCosts.
