### ISSUE TITLE
max distance feature 

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#292]
ToDo
- [ ] max distance feature assumes static travel distance. it should be adjusted to the general case
- [ ] handle additional distance of pickup act. if the vehicle does not need to return to depot then additional distance of pickup act is not calculated correctly. Also when newAct is DeliverShipment, additional distance of PickupShipment should consider distance calc with newVehicle.
- [ ] When actBeforePickup is Start, I don't think we should set it to iFacts.getRoute().getStart(), because the new vehicle start location and departure time could be different from those of the route start;

Thanks He for detecting this.

**Comment by oblonski** [comment]
handle additional distance of pickup act. if the vehicle does not need to return to depot then additional distance of pickup act is not calculated correctly.

**Comment by jsroyal** [comment]
@oblonski 
Some of the issues still open even after the merged. Please closed this issue.
