### ISSUE TITLE
travel time does not match estimated arrival/departure times

### ISSUE THREAD

**Issue by njLT** [graphhopper/jsprit#315]
Hi,
I am using a custom cost matrix along with time windows. The travel time from activity A to activity B takes 2670733.642578125 units. The endTime for activity A is 1480497535364. The endTime for activity B is 1480500392000. The operation time for activity B is 300000. The difference between the start time of B and end time of A comes to 2556636.

The constraints used are the default time windows constraints.
`		ConstraintManager constraintManager = new ConstraintManager(vrp, stateManager);
		constraintManager.addLoadConstraint();
		constraintManager.addTimeWindowConstraint();`

**Comment by oblonski** [comment]
Can we discuss this here please: https://discuss.graphhopper.com/?
