### ISSUE TITLE
Index of vehicle effecting solution

### ISSUE THREAD

**Issue by mndpsngh21** [graphhopper/jsprit#320]
if we change index of vehicle of multiple type is changed then output of solution is also changing.
for example if I have 9 Deliveries and 3 vehicle with capacity of 4,4,6  and cost 4,4,6 respectively. if we add vehicle with following combination like (4,4,6) (4,6,4) or (6,4,4) then sometime solution is different.

**Comment by oblonski** [comment]
I do not understand your problem. Can you give a simple example so we can reproduce this?

**Comment by oblonski** [comment]
let us move this to https://discuss.graphhopper.com/ until it becomes a concrete issue. @mndpsngh21 would you mind to discuss it there?
