### ISSUE TITLE
Solving Loop super problem using Jsprit

### ISSUE THREAD

**Issue by ShivKJ** [graphhopper/jsprit#323]
Hi,
I am wondering if we could solve the following problem using Jsprit,

n- bikers with m- vans are send from Depot so that whenever a bike is loaded with shipment and requires to unload it, it goes to nearby van, and unload the shipment(kind of Delivery) instead of going back to depot. Also note that there are some place where van can not visit(skill feature)

**Comment by oblonski** [comment]
Intersting problem. Would you mind to post this here: https://discuss.graphhopper.com/c/jsprit. Thanks.
