### ISSUE TITLE
Asymmetric Cost Matrix

### ISSUE THREAD

**Issue by Valdecy** [graphhopper/jsprit#326]
Hello! When a custom distance/time matrix is used with asymmetric values to solve a simple TSP, let's say: from 1 to 2 = 10 and from 2 to 1 = 5 (with cost per distance = 1). The solver returns as the solution a total cost equal 10. Meaning that it used the value from 2 to 1, twice. For real distances, this behavior is undesired because some streets or highways may have only one direction for traffic. There is a way to enforce a constraint that differentiates  (i,j) from (j,i) ?

Thanks and Congratulations! This a fantastic project!

Best Wishes,
Valdecy

**Comment by Valdecy** [comment]
Found it!

VehicleRoutingTransportCostsMatrix.Builder costMatrixBuilder = VehicleRoutingTransportCostsMatrix.Builder.newInstance(false); // For asymmetric matrices


VehicleRoutingTransportCostsMatrix.Builder costMatrixBuilder = VehicleRoutingTransportCostsMatrix.Builder.newInstance(true); // For symmetric matrices

Sorry guys...

**Comment by AshwinTayson** [comment]
I was about to ask the same question right now. Luckily I stumbled into this. Thank you

**Comment by brucefeng10** [comment]
Yes, if you choose false(asymmetric matrix), you have to customize all (from, to) values, that is n*(n-1) pairs in total, not just several specific pairs.
