### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by karussell** [graphhopper/jsprit#328]
The links here still point to the wiki:

https://github.com/graphhopper/jsprit/blob/master/docs/Classical-Problems-Examples.md

There are a few more that you can find out via
```
grep wiki docs/*
```

**Comment by jsroyal** [comment]
Hi! @karussell
Is this broken link from the repository?
If I'm correct the please review the PR.

**Comment by jsroyal** [comment]
It has been solved .Need to close this issue
#350
