### ISSUE TITLE
Add units to docs

### ISSUE THREAD

**Issue by atmikev** [graphhopper/jsprit#333]
I can't seem to find the units (time, distance, velocities, etc) in the docs. Found some in variable names while looking through various classes, but it would be great if they were prominently displayed wherever they are used. Sorry if they're actually in the docs somewhere and I've just missed them!

**Comment by oblonski** [comment]
The reason why this does not appear in the docs is that no units are required. You decided which units you want to use. But maybe it is exactly this what is missing in the docs (apart from the fact that the docs are rather inclomple anyway - we definitely need to improve this).

**Comment by atmikev** [comment]
@oblonski `VehicleTypeImpl.Builder`'s `setMaxVelocity` explicitly calls out using meters per second in the doc and parameter name. Is that not accurate anymore?
