### ISSUE TITLE
How can I use a fixed sequence of jobs?

### ISSUE THREAD

**Issue by arielmoraes** [graphhopper/jsprit#340]
The API documention shows how to do this using the `in_sequence `and the `in_direct_sequence `modifiers, but how can I do this using the java code? Thank you.

**Comment by quiqua** [comment]
Those are only available in the Graphhopper RouteOptimization API, but Stefan posted something similar a while back covering different use cases:
http://stackoverflow.com/a/24467964

Maybe this will serve you as an inspiration.

**Comment by arielmoraes** [comment]
Oh that's perfect! Thank you. Besides, is it better to use a Soft Constraint based on costs or a Hard one for this kind of problem?

**Comment by oblonski** [comment]
I use hard constraints. Please use [the forum](https://discuss.graphhopper.com/) for such questions. Thanks.
