### ISSUE TITLE
How do i use the SoftConstraint?

### ISSUE THREAD

**Issue by NaglfarZZ** [graphhopper/jsprit#352]
Hello,
How do i use the SoftConstraint? And How do i make sure the SoftConstraint work?

**Comment by oblonski** [comment]
Please use the forum (discuss.graphhopper.com) for these questions.

**Comment by NaglfarZZ** [comment]
sorry.

2017-06-11 2:38 GMT+08:00 Stefan Schröder <notifications@github.com>:
