### ISSUE TITLE
Time/Distance matrix calculation and How to take traffic into consideration?

### ISSUE THREAD

**Issue by keymo13** [graphhopper/jsprit#353]
Hello,

I have checked other threads, and couldn't find a direct answer to this question, in the time/distance matrix calculated, can we:

1) provide a Time/Distance Matrix calculated by a map provider such as Google Maps or Here Maps ?
2) how to incorporate traffic information (mainly reduced speed limits) with the Time/Distance matrix ?

An approach that occurs on mind is to create 3 Time/Distance matrices for all locations, each representing a period of the day, say 08:00 to 12:00 , 12:00 to 16:00, 16:00 to 20:00 for example, and then rely on different matrices depending on Start time, arrival time and departure time.

thank you.

**Comment by oblonski** [comment]
Interessting! Thanks. Would you mind to post it in our forum: discuss.graphhopper.com

**Comment by keymo13** [comment]
@oblonski sure, I'll post this on the discussion form.
