### ISSUE TITLE
Bug: Extended problem with initial solution

### ISSUE THREAD

**Issue by balage1551** [graphhopper/jsprit#354]
This problem comes from the forum [entry](https://discuss.graphhopper.com/t/assigning-a-job-to-a-specific-vehicle-only-by-applying-hard-constraint/2041/6?u=balage1551).

There were a run with 2 jobs. The best solution is stored.
Then there is a new problem where 

- the vehicles come from the original problem
- the initial solution is the best solution of the original problem
- the jobs come from the original problem, but one more job is added, which can't be fulfilled by the original route.

The result is inconsistent: it doesn't assign the job to the other, unused vehicle, but shows no unassigned jobs, either.

Code:

    package hu.vissy.forum;
    
    import java.util.Arrays;
    import java.util.Collection;
    
    import com.graphhopper.jsprit.analysis.toolbox.GraphStreamViewer;
    import com.graphhopper.jsprit.analysis.toolbox.GraphStreamViewer.Label;
    import com.graphhopper.jsprit.analysis.toolbox.Plotter;
    import com.graphhopper.jsprit.core.algorithm.VehicleRoutingAlgorithm;
    import com.graphhopper.jsprit.core.algorithm.box.Jsprit;
    import com.graphhopper.jsprit.core.algorithm.state.StateManager;
    import com.graphhopper.jsprit.core.problem.Location;
    import com.graphhopper.jsprit.core.problem.VehicleRoutingProblem;
    import com.graphhopper.jsprit.core.problem.constraint.ConstraintManager;
    import com.graphhopper.jsprit.core.problem.constraint.HardRouteConstraint;
    import com.graphhopper.jsprit.core.problem.job.Service;
    import com.graphhopper.jsprit.core.problem.misc.JobInsertionContext;
    import com.graphhopper.jsprit.core.problem.solution.VehicleRoutingProblemSolution;
    import com.graphhopper.jsprit.core.problem.vehicle.VehicleImpl;
    import com.graphhopper.jsprit.core.problem.vehicle.VehicleImpl.Builder;
    import com.graphhopper.jsprit.core.problem.vehicle.VehicleType;
    import com.graphhopper.jsprit.core.problem.vehicle.VehicleTypeImpl;
    import com.graphhopper.jsprit.core.reporting.SolutionPrinter;
    import com.graphhopper.jsprit.core.reporting.SolutionPrinter.Print;
    import com.graphhopper.jsprit.core.util.Coordinate;
    import com.graphhopper.jsprit.core.util.ManhattanCosts;
    import com.graphhopper.jsprit.core.util.Solutions;
    
    public class MultipleTimeWindowExample{
        static class HarConstraintWindows implements HardRouteConstraint{
            HarConstraintWindows( )
            {
            }
    
    
            @Override
            public boolean fulfilled(JobInsertionContext iContext) {
                return true;
            }
        }
    
        public static void main(String[] args) {
    
            /*
             * get a vehicle type-builder and build a type with the typeId "vehicleType" and one capacity dimension, i.e. weight, and capacity dimension value of 2
             */
            final int WEIGHT_INDEX = 0;
            VehicleTypeImpl.Builder vehicleTypeBuilder = VehicleTypeImpl.Builder.newInstance("vehicleType")
                            .addCapacityDimension(WEIGHT_INDEX, 10).setCostPerWaitingTime(1.);
            VehicleType vehicleType = vehicleTypeBuilder.build();
    
    
            /*
             * get a vehicle-builder and build a vehicle with type "vehicleType"
             */
            Builder vehicleBuilder1 = VehicleImpl.Builder.newInstance("1");
            vehicleBuilder1.setStartLocation(loc(Coordinate.newInstance(7, 7))).setReturnToDepot(false);
            vehicleBuilder1.setType(vehicleType);
            VehicleImpl vehicle1 = vehicleBuilder1.build();
    
            Builder vehicleBuilder2 = VehicleImpl.Builder.newInstance("2");
            vehicleBuilder2.setStartLocation(loc(Coordinate.newInstance(7.3,6.5))).setReturnToDepot(false);
            vehicleBuilder2.setType(vehicleType);
            VehicleImpl vehicle2 = vehicleBuilder2.build();
    
            /*
             * build services at the required locations, each with a capacity-demand of 1.
             */
            Service service1 = Service.Builder.newInstance("1")
                            .addTimeWindow(0,6)
                            .addSizeDimension(WEIGHT_INDEX, 1)
                            .setLocation(Location.newInstance(7.5, 5.3)).build();
    
            Service service2 = Service.Builder.newInstance("2")
                            .addTimeWindow(7, 8)
                            .addSizeDimension(WEIGHT_INDEX, 1)
                            .setLocation(Location.newInstance(8, 6)).setServiceTime(1).build();
    
    
    
    
    
            VehicleRoutingProblem.Builder vrpBuilder = VehicleRoutingProblem.Builder.newInstance();
            vrpBuilder.addVehicle(vehicle1).addVehicle(vehicle2);
            vrpBuilder.addJob(service1).addJob(service2);
    
    
            vrpBuilder.setFleetSize(VehicleRoutingProblem.FleetSize.FINITE);
            vrpBuilder.setRoutingCost(new ManhattanCosts());
            VehicleRoutingProblem problem = vrpBuilder.build();
    
    
    
            // Building the algorithm for the problem
    
            VehicleRoutingAlgorithm algorithm = Jsprit.createAlgorithm(problem);
    
    
    
            //  and search a solution
    
            Collection<VehicleRoutingProblemSolution> solutions = algorithm.searchSolutions();
            VehicleRoutingProblemSolution bestSolution = Solutions.bestOf(solutions);
    
            // Iterating the all the solutions
            Service service3 = Service.Builder.newInstance("3")
                            .addTimeWindow(6, 7)
                            .setPriority(1)
                            .addSizeDimension(WEIGHT_INDEX, 1)
                            .setLocation(Location.newInstance(7.5, 7)).setServiceTime(1).build();
    
    
            VehicleRoutingProblem.Builder tspBuilder = VehicleRoutingProblem.Builder.newInstance();
            tspBuilder.addAllVehicles(problem.getVehicles());
            tspBuilder.addAllJobs(vrpBuilder.getAddedJobs());
            tspBuilder.addJob(service3);
            tspBuilder.setFleetSize(VehicleRoutingProblem.FleetSize.FINITE);
    
            VehicleRoutingProblem tsp = tspBuilder.build();
    
            StateManager stateManager = new StateManager(tsp);
            ConstraintManager constraintManager = new ConstraintManager(problem, stateManager);
            constraintManager.addConstraint(new HarConstraintWindows()); // ,
            // ConstraintManager.Priority.CRITICAL
    
            VehicleRoutingAlgorithm algorithm1 = Jsprit.Builder.newInstance(tsp)
                            .setStateAndConstraintManager(stateManager, constraintManager)
                            .buildAlgorithm();
            algorithm1.setMaxIterations(20000);
            algorithm1.addInitialSolution(bestSolution);
    
            VehicleRoutingProblemSolution tspSolution = Solutions.bestOf(algorithm1.searchSolutions());
    
            /*
             * print nRoutes and totalCosts of bestSolution
             */
            SolutionPrinter.print(tsp, tspSolution, Print.VERBOSE);
    
        }
    
        private static Location loc(Coordinate coordinate) {
            return Location.Builder.newInstance().setCoordinate(coordinate).build();
    
        }
    }

Output:

	+--------------------------+
	| problem                  |
	+---------------+----------+
	| indicator     | value    |
	+---------------+----------+
	| noJobs        | 3        |
	| noServices    | 3        | 
	| noShipments   | 0        | 
	| noBreaks      | 0        | 
	| fleetsize     | FINITE   | 
	+--------------------------+
	+----------------------------------------------------------+
	| solution                                                 |
	+---------------+------------------------------------------+
	| indicator     | value                                    |
	+---------------+------------------------------------------+
	| costs         | 7.0                                      | 
	| noVehicles    | 1                                        | 
	| unassgndJobs  | 0                                        | 
	+----------------------------------------------------------+
	+--------------------------------------------------------------------------------------------------------------------------------+
	| detailed solution                                                                                                              |
	+---------+----------------------+-----------------------+-----------------+-----------------+-----------------+-----------------+
	| route   | vehicle              | activity              | job             | arrTime         | endTime         | costs           |
	+---------+----------------------+-----------------------+-----------------+-----------------+-----------------+-----------------+
	| 1       | 2                    | start                 | -               | undef           | 0               | 0               |
	| 1       | 2                    | service               | 1               | 1               | 1               | 1               |
	| 1       | 2                    | service               | 2               | 2               | 8               | 7               |
	| 1       | 2                    | end                   | -               | 8               | undef           | 7               |
	+--------------------------------------------------------------------------------------------------------------------------------+

**Comment by balage1551** [comment]
I'm checking it.

**Comment by balage1551** [comment]
Some positive test cases:

1. When the new job can be inserted into the original route, it is inserted.
2. When no initial solution set, it works.

**Comment by balage1551** [comment]
I've altered the code of `com.graphhopper.jsprit.core.algorithm.VehicleRoutingAlgorithm.verify(VehicleRoutingProblemSolution)`:

    private void verify(VehicleRoutingProblemSolution solution) {
        Set<Job> allJobs = new HashSet<Job>(problem.getJobs().values());
        allJobs.removeAll(solution.getUnassignedJobs());
        for (VehicleRoute route : solution.getRoutes()) {
            allJobs.removeAll(route.getTourActivities().getJobs());
            if (route.getVehicle().getIndex() == 0)
                throw new IllegalStateException("vehicle used in initial solution has no index. probably a vehicle is used that has not been added to the " +
                                " the VehicleRoutingProblem. only use vehicles that have already been added to the problem.");
            for (TourActivity act : route.getActivities()) {
                if (act.getIndex() == 0)
                    throw new IllegalStateException("act in initial solution has no index. activities are created and associated to their job in VehicleRoutingProblem\n." +
                                    " thus if you build vehicle-routes use the jobActivityFactory from vehicle routing problem like that \n" +
                                    " VehicleRoute.Builder.newInstance(knownVehicle).setJobActivityFactory(vrp.getJobActivityFactory).addService(..)....build() \n" +
                                    " then the activities that are created to build the route are identical to the ones used in VehicleRoutingProblem");
            }
        }

        solution.getUnassignedJobs().addAll(allJobs);

        //        if (nuJobs != problem.getJobs().values().size()) {
        //            logger.warn("number of jobs in initial solution ({}) is not equal nuJobs in vehicle routing problem ({})" +
        //                "\n this might yield unintended effects, e.g. initial solution cannot be improved anymore.", nuJobs, problem.getJobs().values().size());
        //        }
    }

This collects all new jobs (not in the original solution) and adds as unassigned jobs to the solution. It solved the inconsistency, but the job isn't assigned. It seems that any vehicle not in the initial solution won't be used in the optimalization. (Still searching the reason.)

By the way, in the code there is a check commented out which warns for some anomalies when new jobs added. So the problem is not new. ;-)

**Comment by oblonski** [comment]
I just flew over the code (without actually running it) and realized that bestSolution does not contain the new job. Therefore bestSolution might be evaluated significantly better than any new solution containing an additional job. Therefore, to make it comparable, you need to add this new service as unassigned job bestSolution and reevaluate bestSolution again.

**Comment by balage1551** [comment]
I've found the first step: adding as unassigned. That's the change I've made above.

**Comment by balage1551** [comment]
The main problem, that it seems the algorithm will not use any vehicles unused in the initial solution.

**Comment by balage1551** [comment]
@oblonski Oh, I understand now what you said, Stefan.
The initial solution as the best solution brings its original cost as well. I only need to recalculate cost in verify after the unassigned  added. :-) I'll figure it out how to do. :-D

**Comment by oblonski** [comment]
@balage1551 Can we close this?

**Comment by balage1551** [comment]
Yes, with notion about some tasks still to do: remove jobs from route.
