### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by husnikadam** [graphhopper/jsprit#356]
Whole project can't be build (specific project - jsprit-instances) using NetBeans maven build. 
Error:

> Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jsprit-instances: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
> Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_102\jre\bin\java" -Xmx100m -Xms100m -jar "C:\Users\uzivatel\Desktop\jsprit project\jsprit\jsprit-instances\target\surefire\surefirebooter7417181767903512583.jar" "C:\Users\uzivatel\Desktop\jsprit project\jsprit\jsprit-instances\target\surefire\surefire9175455957217345743tmp" "C:\Users\uzivatel\Desktop\jsprit project\jsprit\jsprit-instances\target\surefire\surefire_24998004585633268812tmp""
> -> [Help 1]
> 
I'm sure I did everything 100% correctly - I've just downloaded git repository from master branch, opened using netbeans and builded.

**Comment by jsroyal** [comment]
Hey! @husnikadam Sorry I did not get you what is the problem with the building can you please update you above commit What is exact error cause and If possible put screen shot.
I think you have been all doc. If miss then please [visit](https://github.com/graphhopper/jsprit/blob/master/docs/Getting-Started.md)
And there is also the [forum](https://discuss.graphhopper.com/) to get help.
