### ISSUE TITLE
Cannot set vehicle's index

### ISSUE THREAD

**Issue by calfzhou** [graphhopper/jsprit#357]
I see that the [MaxDistanceConstraint](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java#L58) uses vehicle.getIndex(), but there is no public setIndex() or similar method in VehicleImpl class. 

Its parent class `AbstractVehicle` has setIndex() method but is protected, cannot used by users.

VehicleImpl.Builder neither has setIndex().

Then how could I set index value to a vehicle, and how can i use MaxDistanceConstraint ?

**Comment by oblonski** [comment]
> Its parent class AbstractVehicle has setIndex() method but is protected, cannot used by users.

This is intended since the index is assigned internally.

**Comment by oblonski** [comment]
> Then how could I set index value to a vehicle, and how can i use MaxDistanceConstraint ?

Why do you want to set the index? It has an index. Use it as it is.

**Comment by calfzhou** [comment]
I'm trying to use MaxDistanceConstraint, and I have to provide a <vehicle, max distance> mapping. Don't know how to build it, because when adding vehicles to problem, there is no index for each vehicle.

**Comment by oblonski** [comment]
Indices are assigned when building the vehicle routing problem. When using [MaxDistanceContraint](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java) you only need to provide a mapping from vehicle to maxDistance, vehicle1 --> 1000. Then to memorize it in an array the vehicle to index mapping is done internally [here](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java).

**Comment by calfzhou** [comment]
Thanks @oblonski . Because the max distance is vehicle type related in my case, i was trying to let vehicles of the same type use the same index, to reduce the size of <vehicle, max distance> mapping.

**Comment by oblonski** [comment]
I do not know how many vehicles you have, but I assume it does not make any difference. Even with many vehicles of the same type, the size of the map as well as the time it takes to index vehicle --> maxDistance is negligible.

**Comment by oblonski** [comment]
can we close here?

**Comment by calfzhou** [comment]
ok, thanks!

**Comment by calfzhou** [comment]
@oblonski , sorry but I have one more question: when using MaxDistanceConstraint, I need create a state id, but do I need write my own state updater for this state? I did't see where update its data.

The following is a piece of code I find in jsprit test code, it defines a state id named "max-distance", but no state updater is added.

``` java
        StateManager stateManager = new StateManager(vrp);
        ConstraintManager constraintManager = new ConstraintManager(vrp, stateManager);
        StateId maxDistance = stateManager.createStateId("max-distance");
        Map<Vehicle, Double> distMap = new HashMap<>();
        distMap.put(vehicle, 100d);
        MaxDistanceConstraint distanceConstraint = new MaxDistanceConstraint(stateManager, maxDistance, new TransportDistance() {
            @Override
            public double getDistance(Location from, Location to, double departureTime, Vehicle vehicle) {
                return vrp.getTransportCosts().getTransportCost(from, to, departureTime, null, vehicle);
            }
        }, distMap);
        constraintManager.addConstraint(distanceConstraint, ConstraintManager.Priority.CRITICAL);
```

**Comment by calfzhou** [comment]
Now i meet null pointer exception at [this line](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java#L79), where sometimes `currentDistance` is null.

**Comment by calfzhou** [comment]
fixed by using `VehicleDependentTraveledDistance` state updater.

**Comment by kaleeswaran14** [comment]
Complete code snippet MaxDistanceConstraint

`
StateManager stateManager = new StateManager(problem);
ConstraintManager constraintManager = new ConstraintManager(problem, stateManager);
StateId maxDistance = stateManager.createStateId("max-distance");

Map<Vehicle, Double> distMap = new HashMap<>();
distMap.put(vehicle1, 15d);

MaxDistanceConstraint distanceConstraint = new MaxDistanceConstraint(stateManager, maxDistance, problem.getTransportCosts(), distMap);        

Collection<Vehicle> vehicles = new ArrayList<Vehicle>();
vehicles.add(vehicle1);
vehicles.add(vehicle2);
vehicles.add(vehicle3);

stateManager.addStateUpdater(new VehicleDependentTraveledDistance(problem.getTransportCosts(), stateManager, maxDistance, vehicles));

constraintManager.addConstraint(distanceConstraint, ConstraintManager.Priority.CRITICAL);

VehicleRoutingAlgorithm algorithm = Jsprit.Builder.newInstance(problem).setStateAndConstraintManager(stateManager, constraintManager).buildAlgorithm();
`
