### ISSUE TITLE
Declare `getUserData()` in interface Job

### ISSUE THREAD

**Issue by calfzhou** [graphhopper/jsprit#358]
The `userData` from v1.7.2 is a pretty useful feature, thanks for that!

I found that `getUserData()` is not declared in interface Job, but only abstract class AbstractJob. When using this data, I have to cast a job instance to AbstractJob first. Could you please declare this method in the interface? Vehicle and VehicleType interface both declared this method.

**Comment by oblonski** [comment]
Please read the comments from here: https://github.com/graphhopper/jsprit/pull/348

**Comment by oblonski** [comment]
Thus, it will be available in jsprit v2.0
