### ISSUE TITLE
Bike Sharing Rebalancing Problem as VRP with pickups and deliveries

### ISSUE THREAD

**Issue by elloza** [graphhopper/jsprit#365]
Hello everyone!

First of all thank you for your time :)

I was wondering if it is possible to implement the Bike Sharing Rebalancing problem as a kind of VRP problem.

The idea of the problem is the following:

Multiple customers who have shipments and deliveries (The bike stations which need be rebalanced taking or putting bikes).

The trucks have a fixed capacity (e.g 10 bikes).

In this case, the transported commodity is the same. For instance, bikes picked from a station could be put in other station in the same route. In VRP with deliveries, the deliveries are taken at the beginning,  in the depot.

I found [some paper](https://estudogeral.sib.uc.pt/bitstream/10316/35509/1/An%20Intelligent%20Bike-Sharing%20Rebalancing%20System.pdf) which uses JSprit to solve this problem but I don't know how to implement it :(

Please, if some of you could give me some light or example to start I will be very grateful.

Thanks so much in advance!

**Comment by oblonski** [comment]
Thanks for this. Please ask these kind of questions at discuss.graphhopper.com
