### ISSUE TITLE
Transport time is not considered in solution

### ISSUE THREAD

**Issue by kschingiz** [graphhopper/jsprit#377]
I have started topic about this issue here: [discuss.graphhopper.com/](https://discuss.graphhopper.com/t/why-transport-time-is-not-considered-in-solution/2448)
Issue is that if I use VehicleRoutingTransportCostsMatrix for VRP then transport time is ok, but if use ManhattanCosts or EuclideanCosts or something else, then transport time is not considered in solution.
Usage of [ManhattanCosts](https://pastebin.com/4j6RLLM0) solution is [incorrect](https://pastebin.com/rjsUpiSE) 
because end time of the service is equal to arrival time of the next service, there is kms between this services, so we can't teleport from one location to another.

My temp solution is the usage of [VehicleRoutingTransportCostsMatrix](https://pastebin.com/tZmVjaBT) then [solution is correct](https://pastebin.com/3cbHaEfU)

**Comment by kschingiz** [comment]
Full code with 2 cases is here: [pastebin](https://pastebin.com/6y7AaCUM)

I am sorry for the external links..

**Comment by oblonski** [comment]
Thanks for reporting @kschingiz. Would you mind to setup a simple unit test that reproduces this? Just setup ManhattanCosts and your expectation about what ManhattanCosts should return much like this:

`assertEqual(10, manhattanCosts.getTransportTime(..))`

Thanks.

**Comment by kschingiz** [comment]
@oblonski manhattanCosts.getTransportTime(..) returns me correct values, as you see in previous code listings, the problem occurs when I use these costs. I will setup unit test as soon as possible.

**Comment by oblonski** [comment]
Is this still an issue?

**Comment by kschingiz** [comment]
@oblonski I am sorry to be late. We can close, I have solved this. My time and speed units were not consistent in project.

**Comment by oblonski** [comment]
Ok. Super.
