### ISSUE TITLE
Possible bug in maxShare and minShare

### ISSUE THREAD

**Issue by kschingiz** [graphhopper/jsprit#379]
Don't know exactly is this a bug, but here:
https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/box/Jsprit.java#L220
in lines 220 and 221 you define maxShare_ and minShare_ integers, but they are equal:
```
int minShare_ = (int) Math.min(70, Math.max(5, vrp.getJobs().size() * 0.5));
int maxShare_ = (int) Math.min(70, Math.max(5, vrp.getJobs().size() * 0.5));
```
but in 212 and 213 you are declaring maxShare and minShare these way:
```
int minShare = (int) Math.min(20, Math.max(3, vrp.getJobs().size() * 0.05));
int maxShare = (int) Math.min(50, Math.max(5, vrp.getJobs().size() * 0.3));
```
The question is: should minShare_ and maxShare_ be equal?

**Comment by oblonski** [comment]
Thanks @kschingiz. It is no bug. min and max is just equal in this configuration here.
