### ISSUE TITLE
convenience methods in Shipment.Builder

### ISSUE THREAD

**Issue by michalmac** [graphhopper/jsprit#381]
There are already methods like Service.Builder.addAllRequiredSkills() and addAllSizeDimensions()
To ensure more symmetry, would be good to have them in Shipment.Builder as well.
Related to #380

**Comment by oblonski** [comment]
just added https://github.com/graphhopper/jsprit/commit/d573146e35587fdb6bd849ab1a74953bfae157e8 :D
