### ISSUE TITLE
jsprit in Employee Transportation

### ISSUE THREAD

**Issue by Sunanndan** [graphhopper/jsprit#385]
Hi,

I am using jsprit for employee transportation auto routing.
I am passing no. of vehicles and capacity and employee list to drop or pick. Jsprit is creating multiple auto routes according to capacity.
My Drop auto route is according to what we need but getting problem in pickup.
My start location is X which is mandatory. I am not specifying end location as it is not mandatory. I tried using depot as true and false also but to no use.
For pickup, it is not doing proper routing.

My question is whether Jsprit can be used to do auto routing for employee pick and drop facility?

**Comment by oblonski** [comment]
would you mind to discuss this here: discuss.graphhopper.com. Thanks.
