### ISSUE TITLE
mvn clean install issue

### ISSUE THREAD

**Issue by theoneandonlywoj** [graphhopper/jsprit#395]
I follow instructions given in: 
[https://github.com/graphhopper/jsprit/blob/master/docs/Getting-Started.md](url)

I have Java 1.8, Maven 3.5.2

Yet, I get following error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jsprit-instances: 
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?                                                           [ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_151\jre\bin\java" -Xmx100m -Xms100m -jar "D:\1 GitHub\BLINX\________fleet optimization\jsprit\jsprit-instances\target\surefire\surefirebooter7622550068024136438.jar" "D:\1 GitHub\BLINX\________fleet optimization\jsprit\jsprit-instances\target\surefire\surefire2242851532020504905tmp" "D:\1 GitHub\hobbyProjects\________fleet optimization\jsprit\jsprit-instances\target\surefire\surefire_26274983510508290996tmp"" `

Failsafe-summary.xml is as below:
`<?xml version="1.0" encoding="UTF-8"?>
<failsafe-summary result="254" timeout="false">
  <completed>0</completed>
  <errors>0</errors>
  <failures>0</failures>
  <skipped>0</skipped>
  <failureMessage/>
</failsafe-summary>`

Any ideas why it happens?

**Comment by oblonski** [comment]
@arcyfelix Could you manage to install jsprit?

**Comment by arcyfelix** [comment]
@oblonski sadly, not.

**Comment by oblonski** [comment]
Can you build jsprit-core yourself?
