### ISSUE TITLE
Regarding cost of the jsprit routes

### ISSUE THREAD

**Issue by rajatagarwal2** [graphhopper/jsprit#404]
Hi, 
I am confused about the cost that is returned in the jsprit output.
I need to know that whether it is in meters/kilometers/seconds/hours/minutes?

**Comment by oblonski** [comment]
You determine the measurement of costs by setting the parameters of [VehicleType](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/vehicle/VehicleType.java#L55) ([here](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/vehicle/VehicleTypeImpl.java#L169-L242)).
