### ISSUE TITLE
duplicate vehicle type ids are allowed

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#411]
Currently jsprit does not forbid duplicate vehicle type id, thus one can define multiple vehicle types with the same id but with different properties such as cost parameters, like I did in the example provided at the end of this post.

In the example, the fleet manager will always use v2 because it thinks v1 and v2 are with the same vehicle type, and it leads to non-optimal solution.

vrp.getTypes() returns only vehicleType1, because jsprit considers two vehicle-types are equal if they have the same typeId.

[[typeId=type][capacity=[noDimensions=1][[dimIndex=0][dimValue=0]]][costs=[fixed=0.0][perTime=0.0][perDistance=1.0][perWaitingTimeUnit=0.0]]]

When I changed the type id of vehicleType2 to a different one, I would get the optimal solution, and vrp.getTypes() would return two vehicle types.

Thanks @jie31best for detecting

**Comment by oblonski** [comment]
see https://discuss.graphhopper.com/t/bug-with-duplicate-vehicle-type-id/2819

**Comment by oblonski** [comment]
@jie31best This should fix this issue. Would you mind to check it with your example also? Thanks a lot.

**Comment by jie31best** [comment]
@oblonski it works good on my example. Thanks a lot. 👍

**Comment by oblonski** [comment]
Perfect. Thank YOU 👍
