### ISSUE TITLE
Is jsprit extensible so I can add my own algorithms?

### ISSUE THREAD

**Issue by cfoch** [graphhopper/jsprit#415]
Hello, I want to implement some algorithms from some papers. But jsprit already has much stuff well-done for example the definition of vehicle types, instances of it, services, reports, etc. To add my own algorithm do I have to modify jsprit source code or is jsprit extensible so I don't need to even touch jsprit source code?

**Comment by oblonski** [comment]
This should be possible. You can define the VehicleRoutingProblem with jsprit and use it in your own algorithms. If your algorithm returns jsprit's VehicleRoutingProblemSolution, you should also be able to use the analysis tools. These classes alone do not need any specific algorithm, they even do not know that there will be an algorithm using them at all.
I can offer you to help you integrating jsprit's classes and if required generalizing it such that running your own algorithm is easily possible.

**Comment by oblonski** [comment]
There might be specific tools such as the GraphStreamRecorder/Viewer listing to the process of the algorithm. To use these tools you need to offer them to listen to your algorithms too. This might become a bit tricky, but it is definitely not unsolvable.

**Comment by oblonski** [comment]
Which algorithms do you plan to implement? I might be interested in supporting this ;).

**Comment by fowuyu** [comment]
Hello,I also want to implement some algorithms from some papers,like genetic algorithm（GA）,Tabu Search，Simulate Anneal and so on.I hope  read a example code to learn how to implement my own algorithm. Hope to get your reply！Thank you!

**Comment by oblonski** [comment]
Cool! As I wrote above I would be happy to support the integration of alternative algorithms.

**Comment by oblonski** [comment]
@fowuyu Just let me know how I can help you get started.

**Comment by fowuyu** [comment]
Thanks for your reply!I just want to read a demo source code that implement a self-defined algorithm!

**Comment by fowuyu** [comment]
I am research the dynamic pickup and delivery problem with time window and LIFO  restrict.So I need to compare some papers' algorithm.

**Comment by fowuyu** [comment]
@oblonski  Now , I don't know how to do it ,I just read a little source code of jsprit framework.

**Comment by cfoch** [comment]
Hello, basically at least un the short term I am interested on implementing simulated annealing.

**Comment by oblonski** [comment]
@cfoch Sounds good. Let me know if you need help integrating jsprit.
