### ISSUE TITLE
Real Time VRP, Fixed route, need to identify best vehicles type and number of trips

### ISSUE THREAD

**Issue by WaliedA** [graphhopper/jsprit#423]
These routes are predefined and from several pick up point (inbound) and drop off points (outbound), what we are aiming to do is the following:

Identify how many seats/bus types to run each trip.
What trips to be linked at point A based on the proximity of the time intervals between drop/pickup at A
Total number of KM per day, how many no of drivers needed per day as this is 24h operation and max driver shift is 8 hours.
Expanding seat capacity as required in the future and the impact on seats/bus type by trying different types.
[graphhopper_routes1 (1).pdf](https://github.com/graphhopper/jsprit/files/2038876/graphhopper_routes1.1.pdf)

**Comment by oblonski** [comment]
Please ask questions, and use discuss.graphhopper.com for them.
