### ISSUE TITLE
Vehicle Utilization Problem When Planning Jobs At Same Location

### ISSUE THREAD

**Issue by KumarAshish155** [graphhopper/jsprit#424]
If we have added two vehicles to fleet information having below settings :

1. Weight/volume : 30 and 20 respectively
2. Maximum weight of a order to be carried by a vehicle is 15 and 10 respectively

Now if I have 3 orders which need to be planned having weights 14,15 and 05 respectively and same or nearly same location,  it will include only one vehicle having capacity 30 and will auto-route only two orders with 14 and 05 weight.

Now 1 vehicle is not used and 1 order is excluded. Same problem exists with more orders also.

**Comment by quiqua** [comment]
You should probably discuss this at https://discuss.graphhopper.com/c/jsprit

Also it sounds like you need to have a look at your objective function.

**Comment by rahul-algorithmgeek** [comment]
> You should probably discuss this at https://discuss.graphhopper.com/c/jsprit
> 
> Also it sounds like you need to have a look at your objective function.

This issue also occurred for my scenario. Happens when we use different **Skills** and all the load are at **same location**.  I can explain more if needed.
