### ISSUE TITLE
Best way to handle dispatching

### ISSUE THREAD

**Issue by briandilley** [graphhopper/jsprit#437]
I've got a live system with vehicles.  Throughout the day jobs appear that need to be serviced ASAP.  I need to determine which of my X vehicles is the best vehicle to assign this new job to.  Currently I'm just simulating adding the job to every existing vehicle's route and then choosing the route with the lowest cost - does this make sense?

**Comment by briandilley** [comment]
bump

**Comment by yerzhik** [comment]
> bump

dead repository?

**Comment by quiqua** [comment]
As this is not an issue with the software / bug / ... and more a discussion on how to best setup your algorithm, you should head over to https://discuss.graphhopper.com/c/jsprit and post your question there and/or have a look at the examples as well https://github.com/graphhopper/jsprit/tree/master/jsprit-examples/input .

In general `jsprit` will return the solution which best fits the example taking in consideration all provided constraints, costs and the objective-function.
