### ISSUE TITLE
Get current items selected

### ISSUE THREAD

**Issue by yerzhik** [graphhopper/jsprit#438]
Hi, 

I need to implement the vehicle routing problem but with additional constraint which is the bin packing. 
So every time the algorithm checks if the next item is OK to add to current list of selected items, it should retrieve currently selected items and try to 3D bin pack them plus the new item. If they fit then it should say OK. Can I somehow get such information about currently selected list if items while trying to check if the new item fits?

**Comment by quiqua** [comment]
Each job has a `UserData` object, you can add any data to this as you like:

From the `WHATS_NEW` document:

```
2017-06-08 new release v1.7.2

one can now set custom properties/user defined data (see pr: https://github.com/graphhopper/jsprit/pull/348)
For example, if one wants to enrich a service with an arbitrary number of custom properties, set a map like this:

Service one = Service.Builder.newInstance("s").setLocation(Location.newInstance("loc"))
    .setUserData(new HashMap<String, Object>()).build();
```


When creating your new constraint, you can then access all inserted jobs for the current iteration and thus their custom `UserData`.
