### ISSUE TITLE
Drop location issue

### ISSUE THREAD

**Issue by SrinivasTechm** [graphhopper/jsprit#444]
![drop location issue](https://user-images.githubusercontent.com/45195244/48811884-b4c62180-ed6a-11e8-896d-1d3575fb73d9.png)

In the above picture,  Jsprit solution suggests to deliver job3 shipment only at 14:28:06 and Job1 shipment is delivered only with subsequent pickup at 14:39:36 . Is there a way to deliver Job1 shipment together with Job 3 shipment at 14:28:06 hours.
Can any one help on this.

Thanks
Srinivas

**Comment by oblonski** [comment]
Would you mind to ask these questions here: https://discuss.graphhopper.com/c/jsprit
