### ISSUE TITLE
DefaultScorer ignores multiple time windows of the job

### ISSUE THREAD

**Issue by reinterpretcat** [graphhopper/jsprit#446]
Default ScoringFunction implementation seems does not handle nicely scoring for time window param: it always picks the first time window. The issue is applicable for both service and shipment:

```
private double scoreService(InsertionData best, Job job) {
...
    return Math.max(timeWindowParam * (((Service) job).getTimeWindow().getEnd() - ((Service) job).getTimeWindow().getStart()), minTimeWindowScore) +   depotDistanceParam * maxDepotDistance;
}

private double scoreShipment(InsertionData best, Job job) {
...
     double minTimeToOperate = Math.min(shipment.getPickupTimeWindow().getEnd() - shipment.getPickupTimeWindow().getStart(),  shipment.getDeliveryTimeWindow().getEnd() - shipment.getDeliveryTimeWindow().getStart());
...
}

```

I think, ideally it should use time data defined on the corresponding activities, but they are hidden by events abstraction. Still doable, but requires some assumptions and type casting.

**Comment by oblonski** [comment]
@reinterpretcat You are correct. Here we should use an average time window length. Does this make sense?

**Comment by oblonski** [comment]
This should fix it: https://github.com/graphhopper/jsprit/commit/ac84b62651b6c88e537fbfa8eeba95e9bf54872f#diff-c4c1e5f2c1b63221ca16b5f5f4c2f05fR65
Thanks.
