### ISSUE TITLE
add activities to job interface

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#476]
This allows the user to easily retrieve job related information without always turning the job into either a service or a shipment, i.e. we get rid of a number of "instanceof Shipment" stuff.

**Comment by oblonski** [comment]
https://github.com/graphhopper/jsprit/commit/dd3f29b5cc8c6f525ccd617880b1f8fb0a1bb3d9 and related commits

**Comment by oblonski** [comment]
[This](https://github.com/graphhopper/jsprit/commit/ac84b62651b6c88e537fbfa8eeba95e9bf54872f) and [this](https://github.com/graphhopper/jsprit/commit/fe590fc9f80b39083862fca4d270b6b8f5d0e195) illustrates the improvement.

**Comment by quiqua** [comment]
> [This](https://github.com/graphhopper/jsprit/commit/ac84b62651b6c88e537fbfa8eeba95e9bf54872f) and [this](https://github.com/graphhopper/jsprit/commit/fe590fc9f80b39083862fca4d270b6b8f5d0e195) illustrates the improvement.

That looks great! :)

**Comment by oblonski** [comment]
... and it should not break anything even though it is defined in job interface since the job interface is a Schummelinterface. If you want to solve a problem with jsprit, you need to either use Service or Shipment and you are not allowed to implement your own job - as far as I can judge it now.
