### ISSUE TITLE
Set time and distance units

### ISSUE THREAD

**Issue by kstrizhov** [graphhopper/jsprit#489]
Is it possible to configure the units in which solver does the calculatons?

It is not really reasonable in real life to set and solve routing problems  in meters for distances, meters per second for velocities, seconds for times and so on, and it's very confusing to set costs for meter, second etc.

**Comment by oblonski** [comment]
Sure, you decide which units to use. If you want to use km/h, specify your travel time and distance matrix as well as your cost params accordingly.
