### ISSUE TITLE
implement new acceptence criteria

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#493]
as described in https://santini.in/files/papers/santini-ropke-hvattum-2017.pdf

Their general recommendation is to implement the linear version of record-to-record acceptance.

**Comment by oblonski** [comment]
<img width="996" alt="Screenshot 2020-05-13 at 18 32 18" src="https://user-images.githubusercontent.com/5714926/81839650-20e0aa80-9548-11ea-9ed0-c05161e1db39.png">

Source: Santini, A., Ropke, S. & Hvattum, L.M. A comparison of acceptance criteria for the adaptive large neighbourhood search metaheuristic. J Heuristics 24, 783–815 (2018). https://doi.org/10.1007/s10732-018-9377-x

**Comment by oblonski** [comment]
T=(T_start - T_end)/K
T_start=0.0167, T_end=0

**Comment by oblonski** [comment]
You can try out like this:

```
RecordToRecordTravelAcceptance rrt = new RecordToRecordTravelAcceptance();
VehicleRoutingAlgorithm vra = Jsprit.Builder.newInstance(vrp).setCustomAcceptor(rrt).buildAlgorithm();
vra.addListener(rrt);
```

**Comment by ifle** [comment]
@oblonski Do you have general recommendations about using this new acceptance method?
