### ISSUE TITLE
Inconsistent solutions

### ISSUE THREAD

**Issue by VanderIG123** [graphhopper/jsprit#494]
While implementing the code described here:https://github.com/graphhopper/jsprit/blob/master/docs/Simple-Example.md

I noticed that the solutions tend to change depending on the order of insertion of the jobs.
Lets say for example that the optimal solution for 3 jobs: job1,job2 and job3 is job1->job2->job3
If I insert job1 then job2 and then job3 I usually get the optimal solution.

The problem is when I change the order like job2,job1 and then job3 the solution doesn't match the original.

**Comment by rahul-algorithmgeek** [comment]
@VanderIG123  Does the cost also change once the route is created or the cost of both routes are same ?
