### ISSUE TITLE
Distance/duration constraint

### ISSUE THREAD

**Issue by teastares** [graphhopper/jsprit#540]
Is there any way we can constraint the total distance or duration for every route/vehicle?

**Comment by rewertvsp** [comment]
Hi, using MATSim with the extension of jsprit we developed a distance constraint. The published paper you can find here: [https://doi.org/10.1016/j.trpro.2021.01.061](https://doi.org/10.1016/j.trpro.2021.01.061)
With this constraint you can set a max distance for each vehicle type. 
The code is part of the freight extension of MATSim and can be found here: [https://github.com/matsim-org/matsim-libs/tree/master/contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit](https://github.com/matsim-org/matsim-libs/tree/master/contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit)
If you have questions dont hestitate to ask.

**Comment by oblonski** [comment]
https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java
