### ISSUE TITLE
various capacity dimensions

### ISSUE THREAD

**Issue by ghost** [graphhopper/jsprit#55]
currently only one dimension named size or capacity-demand can be set. there might be other dimensions such as both weight and volume, or an arbitrary number of other capacity dimensions.
vehicle-types need to be adapted and jobs that are transported by vehicles

**Comment by kt86** [comment]
The link above to the example is broken. This link works: 
[https://github.com/graphhopper/jsprit/blob/master/jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/TransportOfDisabledPeople.java](https://github.com/graphhopper/jsprit/blob/master/jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/TransportOfDisabledPeople.java)
