### ISSUE TITLE
ASAP vs Less time possible (Feature)

### ISSUE THREAD

**Issue by agausachs** [graphhopper/jsprit#86]
The cost of the total time of different routes, it's the sum of the times per cost per time.
It would be great if you could choose to do the services as fast as possible or in the less time possible.
Let me explain, if I have 2 vehicles, maybe the algorithm finds a fast solution that it's only one route of 30 minutes, leaving the other vehicle without services to do. So, my services will be solved in 30 minutes. But if I want to solve the services in the less time possible, maybe it's a better solution 2 routes of 20 minutes because even the time will be greater (30 vs 40), in 20 minutes everything will be solved.

**Comment by lfreneda** [comment]
@agausachs did you solve it?
