### ISSUE TITLE
Initial loads should be possible and sequence of jobs within a route can change

### ISSUE THREAD

**Issue by jsprit** [graphhopper/jsprit#88]

**Comment by braktar** [comment]
I got something which answer to the initial load part : 
https://github.com/braktar/jsprit/tree/initCap

It have good behavior, but need real cases scenario and some tests too ;)

**Comment by braktar** [comment]
So, I have worked on it and go a bit further.

So what we can do here is : 
Having an initial load (or not) independently for each vehicle and exclude to switch when the initial load is incompatible.
Reload with some pickup once the current and future load allows it.

**Comment by braktar** [comment]
Currently Initial Load are statics but it should be interesting to have way to make it dynamic is a limit too.
Shipments loads are considered has "common" loads so it could be deliver at some points which is not the one expected and load another pickup in replacement, I'll manage to make it a bit stronger for those cases
